# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/zjc/zjc_cpu/zjc_cpu.cache/wt [current_project]
set_property parent.project_path C:/zjc/zjc_cpu/zjc_cpu.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/zjc/zjc_cpu/zjc_cpu.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files c:/file/studentsorting.coe
read_verilog -library xil_defaultlib {
  C:/zjc/zjc_cpu/zjc_cpu.srcs/sources_1/imports/file/EXT.v
  C:/zjc/zjc_cpu/zjc_cpu.srcs/sources_1/imports/file/EXT5.v
  C:/zjc/zjc_cpu/zjc_cpu.srcs/sources_1/imports/file/MIO_BUS.v
  C:/zjc/zjc_cpu/zjc_cpu.srcs/sources_1/imports/file/Multi_CH32.v
  C:/zjc/zjc_cpu/zjc_cpu.srcs/sources_1/imports/file/ctrl_encode_def.v
  C:/zjc/zjc_cpu/zjc_cpu.srcs/sources_1/imports/file/NPC.v
  C:/zjc/zjc_cpu/zjc_cpu.srcs/sources_1/imports/file/PC.v
  C:/zjc/zjc_cpu/zjc_cpu.srcs/sources_1/imports/file/RF.v
  C:/zjc/zjc_cpu/zjc_cpu.srcs/sources_1/imports/file/alu.v
  C:/zjc/zjc_cpu/zjc_cpu.srcs/sources_1/imports/file/clk_div.v
  C:/zjc/zjc_cpu/zjc_cpu.srcs/sources_1/imports/file/ctrl.v
  C:/zjc/zjc_cpu/zjc_cpu.srcs/sources_1/imports/file/dm.v
  C:/zjc/zjc_cpu/zjc_cpu.srcs/sources_1/imports/file/mux.v
  C:/zjc/zjc_cpu/zjc_cpu.srcs/sources_1/imports/file/sccpu.v
  C:/zjc/zjc_cpu/zjc_cpu.srcs/sources_1/imports/file/seg7x16.v
  C:/zjc/zjc_cpu/zjc_cpu.srcs/sources_1/imports/file/SCPU_Top.v
}
read_ip -quiet c:/zjc/zjc_cpu/zjc_cpu.srcs/sources_1/ip/imem/imem.xci
set_property used_in_implementation false [get_files -all c:/zjc/zjc_cpu/zjc_cpu.srcs/sources_1/ip/imem/imem_ooc.xdc]
set_property is_locked true [get_files c:/zjc/zjc_cpu/zjc_cpu.srcs/sources_1/ip/imem/imem.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/zjc/zjc_cpu/zjc_cpu.srcs/constrs_1/imports/file/Nexys4DDR_CPU.xdc
set_property used_in_implementation false [get_files C:/zjc/zjc_cpu/zjc_cpu.srcs/constrs_1/imports/file/Nexys4DDR_CPU.xdc]


synth_design -top IP2SOC_Top -part xc7a100tcsg324-1


write_checkpoint -force -noxdef IP2SOC_Top.dcp

catch { report_utilization -file IP2SOC_Top_utilization_synth.rpt -pb IP2SOC_Top_utilization_synth.pb }
